name: Daily Kosovo Tenders

on:
  schedule:
    - cron: '15 4 * * *'    # Runs daily at 06:15 CET
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tender summariser
        run: python main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Preview CSV
        run: |
          echo "First 10 lines of daily_tenders.csv"
          head -n 10 daily_tenders.csv

