name: Daily Kosovo Tenders

on:
  schedule:
    - cron: '15 4 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      …

